### ISSUE TITLE
Checkbox "Download as JSON" / save as XML

### ISSUE THREAD

**Issue by Martin-de-la-Iglesia** [correspSearch/CMIF-Creator#6] opened 2020-02-19 11:26 UTC
In step 4, when I uncheck "Download as JSON", the "Save" button isn't working anymore. If JSON is the only format to be offered, then the checkbox is unnecessary. However, the manual (https://correspsearch.net/index.xql?id=participate_steps) says, "you can save your CMIF file as XML". Either the save form or the manual should be updated.

**Comment by Jomula** [comment] 2020-10-09 09:20
Dear Martin,

Sorry for the very late reply but I unfortunately only now could return to fix some issues on the CMIF Creator. Could you please provide me with a detailed description of your approach as I cannot reproduce your issue? Is the save-button disabled or is it clickable but simply does not work anymore?

Usually, the CMIF Creator does force you to download JSON if there are any issues with the content you entered during the process (i.e. validation errors). If everything is correct, the JSON-checkbox should uncheck itself, as in that case XML is the preferred format. However, it is possible to download even valid files as JSON, which would mean to recheck the JSON-Checkbox.

In case unchecking the JSON-checkbox leading to save being disabled, there is either a problem with the validation routine, or with the content that was entered beforehands. 

Sorry again for the late reply and best regards
Jonas

**Comment by Martin-de-la-Iglesia** [comment] 2020-10-12 09:11
Dear Jonas,
I think the button was disabled, but I just tried and failed to reproduce the error too.
Best,
Martin

**Comment by Jomula** [comment] 2020-10-12 09:13
Dear Martin,
I am going to close this issue for now then, but if you happen to reencounter the error, please let me know.
Best
Jonas

**Closed as completed** 2020-10-12 09:13 UTC
