### ISSUE TITLE
Wrong CC0 URL

### ISSUE THREAD

**Issue by Martin-de-la-Iglesia** [correspSearch/CMIF-Creator#5] opened 2020-02-19 11:21 UTC
When I select "CC0" as license, the generated link in the CMIF file, "https://creativecommons.org/licenses/by/null/", is dead. Perhaps "https://creativecommons.org/publicdomain/zero/1.0/" would be a better option.

**Comment by Jomula** [comment] 2020-02-19 13:20
Dear Martin,
thank you for your message. We will have a look into the issues asap.
Best regards
Jonas

**Comment by Jomula** [comment] 2020-03-20 08:08
the issue is fixed in the github build. it has yet to be published on correspSearch.

**Closed as completed by Jomula** 2020-03-20 08:08 UTC
